version: '3.9'
services:
  event-stream-filter:
    build: Dockerfile
    command:
      node dist/index.js
    environment:
      - ENV_ID=prod
    ports:
      - 8300:8300
      - 8350:8350
    volumes:
      - .:/app/
    restart: always
    network_mode: host