version: '3.9'
services:
  event-stream-filter:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - ENV_ID=prod
    ports:
      - 8300:8300
      - 8350:8350
    restart: always
    network_mode: host