FROM platformatic/node-caged:25-slim

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm@10.29.2 && pnpm install --frozen-lockfile

COPY . .

EXPOSE 4000
EXPOSE 8300
EXPOSE 8350

CMD ["pnpm", "run", "start"]
