version: '3.9'
services:
  weather:
    build: .
    command:
      node dist/index.js
    ports:
      - 8300:8300
      - 8350:8350
    volumes:
      - .:/app/
    restart: always
    network_mode: host